services:
  - type: web
    name: easyarena-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: OTP_EXPIRES_IN_SECONDS
        value: 300
      - key: OTP_LENGTH
        value: 6
      - key: PAYMENT_PROVIDER_NAME
        value: samirpay
      - key: SAMIRPAY_API_KEY
        sync: false
      - key: SAMIRPAY_SECRET_KEY
        sync: false
      - key: SAMIRPAY_WEBHOOK_SECRET
        sync: false
      - key: SMS_PROVIDER_NAME
        value: mock
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_BUCKET_NAME
        sync: false

